require 'database_cleaner'

DatabaseCleaner.clean_with(:truncation)

# -- EXERCISES -- #

  # STRENGTH TRAINING #

    # ARMS #
    
    Exercise.create(name: "Bicep Curl", exercise_type: "Strength", body_part: "Arms", muscle_group: "Biceps", description: "Begin by standing with feet shoulder width apart, knees slightly bent and abs drawn in. Pick up dumbbells with palm facing inward grip. Curl dumbbell up towards your shoulder, rotating your grip as you go until your palms are facing up. Make sure to keep elbows locked in at your side, and to focus on squeezing and isolating your bicep as much as possible. Slowly reverse the action, rotating your grip and returning the weights to your side. Repeat!")
    Exercise.create(name: "Hammer Curl", exercise_type: "Strength", body_part: "Arms", muscle_group: "Biceps", description: "Similar to the bicep curl, but without rotation. Begin by standing with feet shoulder width apart, knees slightly bent and abs drawn in. Pick up dumbbells with palm facing inward grip. Curl dumbbell up towards your shoulder like holding a hammer. Make sure to keep elbows locked in at your side, and to focus on squeezing and isolating your bicep as much as possible. Slowly reverse the action, returning the weights to your side. Repeat!")
    Exercise.create(name: "Lying Extension", exercise_type: "Strength", body_part: "Arms", muscle_group: "Triceps", description: "Begin by lying down on flat bench with your feet on the floor in front of you, holding a dumbbell in each hand in a neutral grip elevated above your head, arms extended. Slowly lower the dumbbells down towards your face so that they are at level with your ears and hold for a count. Slowly return back to the starting position and repeat!")
    Exercise.create(name: "Dumbbell Bench Press", exercise_type: "Strength", body_part: "Chest", muscle_group: "Chest / Triceps / Shoulders", description: "Start off by picking the dumbbells that you can manage, holding them at your sides and then sitting on the edge of a flat bench. Using your thighs and thrusting of your arms to lift the weights onto your legs in your starting position. Lean back onto the bench and on the motion down, push the dumbbells up about an inch high above your chest as this will be your starting position. The dumbbells should be aligned with the middle of your chest and then slowly push the dumbbells up above your body using mostly your chest and triceps for the motion upward. Stop the motion of the exercise as soon as your arms are straight and the dumbbells are directly above your chest. Squeeze your chest muscles as soon as you reach the top position and hold for a count, then return back to the starting position. On the return motion down, do not let gravity do the work or drop the dumbbells, you should be resisting gravity of the way down.")
    Exercise.create(name: "Standing Lateral Raise", exercise_type: "Strength", body_part: "Shoulders", muscle_group: "Deltoids", description: "Start off standing up straight with your feet shoulder width apart, arms at your sides and holding a dumbbell in each hand. Once in position slowly raise the weights up at your sides till they are at shoulder height avoiding any swinging. Hold this position for a count then return back to the starting position. On the next rep raise the weights out directly in front of you until they are at shoulder level again. Return back to the starting position and repeat.")

    # LEGS #

    Exercise.create(name: "Dumbbell Lunge", exercise_type: "Strength", body_part: "Upper Legs", muscle_group: "Hamstrings / Glutes", description: "Start off grabbing a dumbbell in each hand and standing with your feet about 8 inches apart and toes facing forward as this will be your starting position. Once in position take a step forward (about 2 to 3 feet), keeping your abs tightly drawn and and your upper body straight. Continue forward and slowly lower one knee down towards the ground and keeping the other knee bent at a 90 degree angle, not letting the back knee touch the ground. Slowly lower one knee down as if kneeling while keeping your other knee bent at a 90 degree angle, do not let your knee touch the ground. Hold the position for a count then return back up to the starting position.")
    Exercise.create(name: "Dumbbell Squat", exercise_type: "Strength", body_part: "Upper Legs", muscle_group: "Hamstrings / Glutes", description: "Start off grabbing a dumbbell in each hand, placing your feet slightly wider than shoulder-width apart with your knees and toes pointed outward. Keeping your abs tightly drawn in, slowly descend by bending at your knees and hips in a squatting motion. Continue to slowly lower yourself as far as you can control without letting your body shift towards your toes. Once in the downward position and as far as you can go down, hold for a count and then slowly return to the starting position. Repeat for as many reps and sets as desired.")
    Exercise.create(name: "Bodyweight Lunge", exercise_type: "Strength", body_part: "Upper Legs", muscle_group: "Hamstrings / Glutes", description: "Start off standing up straight with your knees slightly bent then get into a lunge position, and squat down through your hips. Squat down so that your front leg is parallel with the floor and hold for a count. Return back to the starting position. Repeat for as many reps and sets as desired.")
    Exercise.create(name: "Bodyweight Standing Calf Raise", exercise_type: "Strength", body_part: "Lower Legs", muscle_group: "Calves", description: "Start off setting up either a step or a block next to either a support structure or smith machine. Place the balls of your feet on the edge of the block/step and let your heels drop down towards the floor as far as possible. Then slowly raise your heels up as high as possible, squeezing your calves and hold for a count. Return back to the starting position. Repeat for as many reps and sets as desired.")
    Exercise.create(name: "Dumbbell Seated Calf Raise", exercise_type: "Strength", body_part: "Lower Legs", muscle_group: "Calves", description: "Start off sitting down on the end of a flat bench with a block or step positioned right in front of you, and hold a dumbbell on both of your legs. Dip your heels down towards the floor as far as possible as this will be your starting position. Keeping the dumbbells firmly pressed up against your knees, slowly raise your heels up off of the floor as far as possible squeezing your calves and hold for a count. Return back to the starting position. Repeat for as many reps and sets as desired.")

    # CORE #

    Exercise.create(name: "Crunch", exercise_type: "Strength", body_part: "Abs", muscle_group: "Full Core", description: "Start off on the ground, with your legs bent at a 90 degree angle in the air and your hands placed across your chest or on either side of your head. Then slowly raise your upper body (head, shoulders and chest) up off of the floor and towards your knees, squeezing and crunching your abs. Hold this position for a count, squeezing your abs, then return back to the starting position. Make sure to keep your hips straight and your lower back against the floor during this exercise.")
    Exercise.create(name: "Cross Body Crunch", exercise_type: "Strength", body_part: "Abs", muscle_group: "Obliques", description: "The cross-body crunch exercise is a variation of the crunch that works both the upper and lower portion of the abs. Start off lying on your back, bringing your knees up in a 60 degree angle, keeping your feet flat on the floor and placing your hands on either side of your head. Slowly curl up raising your right elbow and your left knee so that they touch over your chest. Curl up raising your right elbow and your left knee so that they touch over your chest.")
    Exercise.create(name: "Air Bike", exercise_type: "Strength", body_part: "Abs", muscle_group: "Obliques", description: "Start off lying flat as if you were going to perform a sit up putting your hands behind your your head and lifting your shoulders into a crunch position. Bring your knees up so that they are perpendicular with the floor and your lower legs are parallel with the ground as this will be your starting position. Slowly go through a cycle pedal motion kicking forward with your right leg and bringing in the knee of the left leg. Next bring your right elbow close to your left knee by crunching to the side. Return back to the starting position as you breathe in then crunch to the opposite side as you cycle your legs and bring your left elbow close to your right knee. Repeat with each side for as many reps and sets as desired.")
    Exercise.create(name: "Jackknife Sit Up", exercise_type: "Strength", body_part: "Abs", muscle_group: "Lower Abs", description: "Start by lying on your back with your arms by your side. Do a sit up while at the same time bringing your legs also to your chest. Try to keep your hands towards the ground. Extend your self flat on the ground. Repeat for the desired amount of reps.")
    Exercise.create(name: "Leg Pull In", exercise_type: "Strength", body_part: "Abs", muscle_group: "Lower Abs", description: "To begin this exercise; start your body off with your back flat on the floor and legs extended and palms down on your side. Take your knees and curl up, pulling your thighs toward your chest as you exhale. Once your knees have hit the chest level, squeeze your abs and hold for a few seconds. Release your contraction and return back to the starting position inhaling down. Repeat this exercise for as many repetitions as needed.")

  # CARDIO #

  Exercise.create(name: "Running", exercise_type: "Cardio", body_part: "Legs", muscle_group: "Legs / Core", description: "Running is one of the most common and effect forms of exercise for muscle toning, weight loss and keeping your lungs and body in shape. Running improves on conditioning the body, endurance, stamina, speed, strength in the legs and core, as well as improving one's posture.")
  Exercise.create(name: "Walking", exercise_type: "Cardio", body_part: "Legs", muscle_group: "Legs / Core", description: "Walking, a form of cardio exercise, can be performed outside or on a treadmill and focuses upon burning calories, strengthening the core and leg muscles and increasing overall endurance and stamina.")
  Exercise.create(name: "Swimming", exercise_type: "Cardio", body_part: "Full Body", muscle_group: "Core / Full Body", description: "Swimming is a great way to tone your body and improve overall fitness. It focuses upon stamina, endurance, core and full body strength, coordination, and burn fat.")
  Exercise.create(name: "Boxing", exercise_type: "Cardio", body_part: "Full Body", muscle_group: "Arms / Core", description: "Boxing is a combat sport in which two people fight one another with their fists, it is a great exercise that helps increase stamina, agility and strength while also helping you lose weight and tone your body.")
  Exercise.create(name: "Jump Rope", exercise_type: "Cardio", body_part: "Legs", muscle_group: "Legs / Core", description: "Jump rope is a great cardio exercise that helps burn a significant amount of calories through repeated jumping motion and keeping the body moving. This exercise helps condition the body for strenuous activity along with increasing endurance, stamina, building strength in the leg muscles and core, and loosening up for other activities.")

# -- USERS -- #

User.create(username: "swb258", first_name: "Sean", last_name: "Brown", age: 28)
User.create(username: "Snowballdog", first_name: "Jeff", last_name: "Brown", age: 30)
User.create(username: "Katzilla912", first_name: "Kat", last_name: "Blackwood", age: 28)
User.create(username: "Shady_Gravy", first_name: "Evan", last_name: "Brown", age: 30)
User.create(username: "Alfidabeast7", first_name: "Alfi", last_name: "Rolon", age: 26)
User.create(username: "Some_Italian_Guy", first_name: "Mike", last_name: "Ruocco", age: 28)

# -- USER EXERCISES -- #

UserExercise.create(user_id: 1, exercise_id: 1)
UserExercise.create(user_id: 1, exercise_id: 2)
UserExercise.create(user_id: 2, exercise_id: 8)
UserExercise.create(user_id: 3, exercise_id: 7)
UserExercise.create(user_id: 4, exercise_id: 6)